### PR TITLE
added ability to set multiple properties by accepting a JS object as a parameter

### PR DESCRIPTION
**Pull request by RaghavRamesh**
In response to the feature request in #61

### CODE REVIEW

**Comment by shuvalov-anton** [comment]
@axelpale what do you think about this PR? I'm confused 'cause I didn't use `move` by this way. hmhm

**Comment by axelpale** [comment]
@RaghavRamesh @shuvalov-anton Basically this seems ok to me because for example [jQuery#css](http://api.jquery.com/css/#css-properties) allows similar input. The PR implements the feature cleanly, although it adds one extra if-comparison to each `.set` call, which, however, is inevitable.

Thinking aloud: Only thing that keeps me thinking is the execution order. For example transformations must be in order to get the correct outcome. Is the same true for css-properties? I think not, css-propertiess are not order dependent. Are the durations applied to each property separately or are they all applied at the same time? Latter is true, implemented in [Move#applyProperties](https://github.com/visionmedia/move.js/blob/master/index.js#L440), which is good.

Therefore I endorse the merge. Any further thoughts?

BTW, later on we should give API docs a little love.

**Comment by RaghavRamesh** [comment]
Any updates on merging this? :)

**Comment by axelpale** [comment]
Thank you for the PR and sorry for the laaaazyyy merge. Generally speaking, accepting a PR is a bit risky business as we do not have unit tests or performance benchmarks.

**Pull request merged**
