### PR TITLE
Add support for percentage values

### LINKED ISSUE #40: Add support for percentage values
I have made a commit here: https://github.com/alkavan/move.js/commit/cd9a80a02c38c567fe7a36ab7710c0730db29fb2

This is an example of modified translateX() and translateY() methods to support passing percent values, for example translateX('60%') or translateX('-60%') would work now.

I think this is something that should be done to all types that support percent values, I can do this because I really need this functionality, but I wonder if you'll pull this changes if I'll add this to all methods, because while I don't really need this for all of methods, someone else might ...

UPDATE: also added to translate() method: https://github.com/alkavan/move.js/commit/d108addf231eaec15dcc075823246f2b20ffbc4d

### PR DESCRIPTION
**Pull request by andrepolischuk**
Add percentage values for translate, fix #40

```js
move('.square')
  .to('50%', '25%')
  .end();
```

### CODE REVIEW

**Comment by yields** [comment]
nice! can we keep the conditionals on one line? otherwise looks good to merge!

**Comment by andrepolischuk** [comment]
I fixed to one line

**Comment by shuvalov-anton** [comment]
@andrepolischuk good catch! But IMHO checking for percent/px by the type of value looks confusing for users. I think, the better way is to add `px` to the value only if user hasn't specified units. For example if user set `-100%` or `20rem` we're just passing it. But if user has just set only digits (no matter string it or integer), then we will add `px` to the value before passing.

Please, can you update behaviour to make it more flexible?

**Comment by shuvalov-anton** [comment]
And one little note — can you move this logic into helper function in the bottom of the file? It's pretty nice place for DRY 'cause of many duplications :D

**Comment by andrepolischuk** [comment]
Sure

**Comment by andrepolischuk** [comment]
@shuvalov-anton Fixed

**Comment by shuvalov-anton** [comment]
Thanks)

**Comment by iamstarkov** [comment]
👍

**Pull request merged**
