### PR TITLE
package.json, npm and browserify support

### PR DESCRIPTION
**Pull request by axelpale**
This pull request solves [issue/41](https://github.com/visionmedia/move.js/issues/41), [issue/42](https://github.com/visionmedia/move.js/issues/42) and [issue/71](https://github.com/visionmedia/move.js/issues/71), the first two relating to missing package.json, missing npm entry and therefore missing browserify support. The issue/41 has many details about the issue and its solution. After the merge, move.js can be downloaded via npm and used with browserify but still continued to be used with component(1) just as before.

After merge, **one more thing is required by you, precious collaborator**: `npm publish`

This pull request includes
- npm installation instructions in Readme.md
- brand new package.json, rewritten from component.json
- replacing `require('emitter')` by `require('component-emitter')` and similar as discussed in [issue/41](https://github.com/visionmedia/move.js/issues/41), providing compatibility for both component(1) and node/commonjs/browserify.
- removing `remotes` from component.json because [*the public component must not contain any remotes*](https://github.com/componentjs/spec/blob/master/component.json/specifications.md#remotes). If `remotes` exists, running `component install` produces error `no remote found for dependency ...`.
- new builds of move.js and move.min.js, built with `make move.js` and `make move.min.js`. Apparently a few extra kilobytes were shaved off as well (28 kB -> 26 kB and 16 kB -> 14 kB).
- Version bumb to 0.5.0, because otherwise some 0.4.0 would work with npm and some would not.

### CODE REVIEW

**Comment by shuvalov-anton** [comment]
+1 @tj @yields can I merge this pull request and publish it to the npm?

**Comment by tj** [comment]
added both of you! LMK what the npm usernames are

**Comment by axelpale** [comment]
@tj Thanks a lot! My npm username is [xeli](https://www.npmjs.com/~xeli).

**Comment by axelpale** [comment]
@shuvalov-anton could you publish, I do not have time available until the weekend. Thanks!

**Comment by shuvalov-anton** [comment]
@th thank you :D `shuvalov-anton`

**Comment by tj** [comment]
apparently I dont have access to the npm module either

**Comment by shuvalov-anton** [comment]
@axelpale both `move` and `movejs` names are occupied. We should find the other one. Do you have ideas? Mb `move.js`?

**Comment by axelpale** [comment]
@shuvalov-anton I would prefer `move-js` because dash seems to be the convention in npm. For example, [search packages with "js"](https://www.npmjs.com/search?q=js) and you get a long list of package names with a dash in them. Same thing happens if you [search for "move"](https://www.npmjs.com/search?q=move).

**Comment by axelpale** [comment]
Btw, I [removed false npm installation instructions from Readme.md](https://github.com/visionmedia/move.js/commit/eec5cbefebaf60bc9f1021e3e97530a852a37105) that got there in this PR. After `npm publish`, the correct installation instructions should be added back, depending on the name, e.g:

...

With [npm](https://www.npmjs.com/package/move-js):

    $ npm install move-js

...

**Comment by shuvalov-anton** [comment]
@axelpale nice. `move-js` ok for me.

**Comment by axelpale** [comment]
@shuvalov-anton Now it is published \o/

**Comment by shuvalov-anton** [comment]
Great! bicho-6

**Pull request merged**
